import type { Metadata } from "next";
import {  Playfair_Display, Inter_Tight  } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter_Tight({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],

});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${playfair.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <Script
          id="disable-scroll-restoration"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `if ('scrollRestoration' in window.history) { window.history.scrollRestoration = 'manual'; } window.scrollTo(0, 0);`,
          }}
        />
        {children}
      </body>
    </html>
  );
}